// FRPG_Filter_FC.fxh - DL_FREG cbuffer for Filter shaders (auto-generated
// from FRPG_Fil_DownScale2x2.fpo reference RDEF; 67 members).
// Declaration order = reference order; types exact.

#ifndef ___FRPG_Filter_FC_fxh___
#define ___FRPG_Filter_FC_fxh___

    float4         DL_FREG_007              : register(c7); // [unused]
    float4         DL_FREG_008              : register(c8); // [unused]
    float4         DL_FREG_009              : register(c9); // [unused]
    float4         DL_FREG_010              : register(c10); // [unused]
    float4         DL_FREG_011              : register(c11); // [unused]
    float4         DL_FREG_012              : register(c12); // [unused]
    float4         DL_FREG_013              : register(c13); // [unused]
    float4         DL_FREG_014              : register(c14); // [unused]
    float4         DL_FREG_015              : register(c15); // [unused]
    float4         DL_FREG_016              : register(c16); // [unused]
    float4         DL_FREG_017              : register(c17); // [unused]
    float4         DL_FREG_018              : register(c18); // [unused]
    float4         DL_FREG_019              : register(c19); // [unused]
    float4         DL_FREG_020              : register(c20); // [unused]
    float4         DL_FREG_021              : register(c21); // [unused]
    float4         DL_FREG_022              : register(c22);
    float4         DL_FREG_023              : register(c23);
    float4         DL_FREG_024              : register(c24);
    float4         DL_FREG_025              : register(c25);
    float4         DL_FREG_026              : register(c26); // [unused]
    float4         DL_FREG_027              : register(c27); // [unused]
    float4         DL_FREG_028              : register(c28); // [unused]
    float4         DL_FREG_029              : register(c29); // [unused]
    float4         DL_FREG_030              : register(c30); // [unused]
    float4         DL_FREG_031              : register(c31); // [unused]
    float4         DL_FREG_032              : register(c32); // [unused]
    float4         DL_FREG_033              : register(c33); // [unused]
    float4         DL_FREG_034              : register(c34); // [unused]
    float4         DL_FREG_035              : register(c35); // [unused]
    float4         DL_FREG_036              : register(c36); // [unused]
    float4         DL_FREG_037              : register(c37); // [unused]
    float4         DL_FREG_038              : register(c38); // [unused]
    float4         DL_FREG_039              : register(c39); // [unused]
    float4         DL_FREG_040              : register(c40); // [unused]
    float4         DL_FREG_041              : register(c41); // [unused]
    float4         DL_FREG_042              : register(c42); // [unused]
    float4         DL_FREG_043              : register(c43); // [unused]
    float4         DL_FREG_044              : register(c44); // [unused]
    float4         DL_FREG_045              : register(c45); // [unused]
    float4         DL_FREG_046              : register(c46); // [unused]
    float4         DL_FREG_047              : register(c47); // [unused]
    float4         DL_FREG_048              : register(c48); // [unused]
    float4         DL_FREG_049              : register(c49); // [unused]
    float4         DL_FREG_050              : register(c50); // [unused]
    float4         DL_FREG_051              : register(c51); // [unused]
    float4         DL_FREG_052              : register(c52); // [unused]
    float4         DL_FREG_053              : register(c53); // [unused]
    float4         DL_FREG_054              : register(c54); // [unused]
    float4         DL_FREG_055              : register(c55); // [unused]
    float4         DL_FREG_056              : register(c56); // [unused]
    float4         DL_FREG_057              : register(c57); // [unused]
    float4x4       DL_FREG_058              : register(c58); // [unused]
    float4x4       DL_FREG_062              : register(c62); // [unused]
    float4         DL_FREG_066              : register(c66); // [unused]
    float4         DL_FREG_067              : register(c67); // [unused]
    float4         DL_FREG_068              : register(c68); // [unused]
    float4         DL_FREG_069              : register(c69); // [unused]
    float4         DL_FREG_070              : register(c70); // [unused]
    float4         DL_FREG_071              : register(c71); // [unused]
    float4         DL_FREG_072              : register(c72); // [unused]
    float4         DL_FREG_073              : register(c73); // [unused]
    float4x4       DL_FREG_074              : register(c74); // [unused]
    float4         DL_FREG_078              : register(c78); // [unused]
    uint4          gFC_FrameIndex           : register(c81); // [unused]
    float4x4       gVC_WorldViewClipMtx     : register(c82); // [unused]
    float4         gVC_ScreenSize           : register(c86); // [unused]
    float4         gVC_NoiseParam           : register(c87); // [unused]

#endif